Add es update oersi
TIBHannover/edu-sharing-box pull request #59
Opened 2024-02-19 16:03 UTC by Edmondi-Kacaj

Hello @mirjan-hoffmann 

I have submitted a pull request that adds the functionality to install and activate the Alfresco module. This module is designed to update Oersi links whenever there are changes in the accessibility of materials from edu-sharing, such as when they transition from public to private or vice versa. Additionally, it handles updates to Oersi when a public material undergoes any modifications. Furthermore, if a public material is restored from the recycle bin, the Oersi is also updated accordingly.

2024-02-19 16:54 UTC, mirjan-hoffmann requested changes

2024-02-19 16:54 UTC, mirjan-hoffmann commented on ansible/group_vars/edusharing.yml
> +# activate/deactivate es-update-oersi, a alfresco plugin used to update oersi links
```suggestion
# activate/deactivate es-update-oersi, a alfresco plugin used to update metadata in oersi
```

2024-02-19 16:54 UTC, mirjan-hoffmann commented on ansible/group_vars/edusharing.yml
> +# oersi update link
```suggestion
# oersi update endpoint 
```

2024-02-19 16:54 UTC, mirjan-hoffmann commented on ansible/group_vars/edusharing.yml
> +# version of the amp filethe
what is the meaning of `filethe`? typo?

2024-02-19 16:54 UTC, mirjan-hoffmann commented on ansible/roles/edu-sharing/tasks/common/es_update_oersi.yml
> +  when: install_alfviral | default(false) | bool
`activate_es_update_oersi` instead of `install_alfviral` ?!

2024-02-19 16:54 UTC, mirjan-hoffmann commented on ansible/roles/edu-sharing/tasks/edu-sharing-docker/edu-sharing-config-file.yml
> +    (install_antivirus is defined ) and ( install_antivirus)
`install_antivirus` does not seem to be correct here

2024-02-19 17:15 UTC, Edmondi-Kacaj commented
Thanks, for having a look, I fixed those small problems

2024-02-20 05:07 UTC, mirjan-hoffmann requested changes

2024-02-20 05:07 UTC, mirjan-hoffmann commented on ansible/roles/edu-sharing/tasks/edu-sharing-docker/es_update_oersi.yml
> +# Include the alfviral amp file
`alfviral` does not seem to be correct here

2024-02-20 05:07 UTC, mirjan-hoffmann commented on ansible/roles/edu-sharing/tasks/edu-sharing-docker/es_update_oersi.yml
> +# Include the alfviral amp file
```suggestion
# Include the es-update-oersi amp file
```

2024-02-20 05:07 UTC, mirjan-hoffmann commented on ansible/roles/edu-sharing/tasks/edu-sharing-docker/es_update_oersi.yml
> +- name: modify reinstall.sh script to accept alfviral amp
```suggestion
- name: modify reinstall.sh script to accept es-update-oersi amp
```

2024-02-20 05:08 UTC, mirjan-hoffmann approved these changes

2024-02-20 05:08 UTC, merged