(Clean up Process) Remove old roles and tasks
TIBHannover/edu-sharing-box pull request #63
Opened 2024-04-26 07:16 UTC by Edmondi-Kacaj

2024-04-26 07:17 UTC, Edmondi-Kacaj commented
Is still in WIP: so no further action here

2024-04-29 16:00 UTC, Edmondi-Kacaj commented
Hello @mirjan-hoffmann ,

I'd like to request your review of the changes in this pull request.

The focus of this pull request is to clean up major roles. However, please note that there may still be some variables or files that have not been deleted. These will be addressed in the next pull request, where I plan to optimize all existing roles and remove any unnecessary components.

2024-04-30 09:01 UTC, mirjan-hoffmann requested changes

2024-04-30 09:01 UTC, mirjan-hoffmann commented on ansible/roles/java/tasks/Debian.yml
Didn't we discuss yesterday that a Java installation is not required on the system, because everything that uses Java is running in Docker Containers? Why do you keep Java here? (I cannot find it documented at the PR)

2024-04-30 09:37 UTC, Edmondi-Kacaj commented on ansible/roles/java/tasks/Debian.yml
Yes java is used in https://github.com/TIBHannover/edu-sharing-box/blob/master/ansible/roles/edu-sharing/tasks/edu-sharing-docker/model.yml#L24C6-L24C161

```yml
   - name: get original files from archive
     shell:
      chdir: '{{ edu_docker_inst_dir }}/custom-repository-service'
      cmd: '{{ java_home }}/bin/jar xf edu_sharing-community-repository-backend-alfresco-module-{{ edu_version }}.amp config/alfresco/extension/{{ item.path }}'
    loop: "{{ (alfresco_ccmodel_add_custom_properties | default([], true)) + (edu_cccontentmodel_adjustments | default([], true)) }}"
```

and for that I adjusted, and we will keep java

2024-04-30 09:40 UTC, Edmondi-Kacaj commented on ansible/roles/backup/tasks/backup-edusharing-docker.yml
Because the old backup for edu-sharing > 7, will work but it's better to use the edu-sharing script for backup and restore provided by Edu-sharing itself, and this will be included in the next pull request

2024-04-30 09:45 UTC, mirjan-hoffmann commented on ansible/roles/backup/tasks/backup-edusharing-docker.yml
Then, I would say, let's remove the backup within the same PR in which you switch to the edu-sharing script. Otherwise the feature is missing in the meanwhile.

2024-04-30 09:46 UTC, Edmondi-Kacaj commented
> We should highlight or point out more, that this PR removes the support for non-Docker or edu-sharing versions -> I'll change the title of this PR

We will document in the README.md file, that we will provide no support anymore for the non-docker 
 edu-sharing, so the title here will be OK even if leave like it is

2024-04-30 09:49 UTC, mirjan-hoffmann commented
> > We should highlight or point out more, that this PR removes the support for non-Docker or edu-sharing versions -> I'll change the title of this PR
> 
> We will document in the README.md file, that we will provide no support anymore for the non-docker edu-sharing, so the title here will be OK even if leave like it is

If someone is looking here in GitHub, then it is better to understand, if we use more meaningful or describing titles

2024-04-30 09:54 UTC, Edmondi-Kacaj commented on ansible/roles/backup/tasks/backup-edusharing-docker.yml
I think it will be a fat pull request if we try to clean and optimize the process same time, so this is why I choose to delete everything we don't need anymore, and focus in next pull request in the optimization, and what is missing to develop based on it.

P.S: if you say let's keep the backup here and delete it in the next pull request then, let's do it

2024-04-30 09:59 UTC, mirjan-hoffmann commented on ansible/roles/java/tasks/Debian.yml
Ok for me. But I suggest to simplify this (maybe in your next optimization-PR??). In the past, we implemented our own solution just to be sure to use a Java-version that fits for edu-sharing. Now, java is not used to run edu-sharing, so we should switch to a solution with less maintenance effort (currently each bugfix version has to be updated manually).
* if possible the java-usages could be made in Docker-Container?
* Otherwise: it would be better to use a Java-Installation from the official Debian-Source-Packages to automatically receive updates.

2024-04-30 10:09 UTC, mirjan-hoffmann commented on ansible/roles/backup/tasks/backup-edusharing-docker.yml
Yes, let's keep the Docker-Backup here. Backup for older, non-Docker versions can be deleted

2024-04-30 10:12 UTC, mirjan-hoffmann commented
And one more thing: role `tomcat` is removed with this PR, but it is still used in role `moodle-registration`. Looks to me like this role is just running for the older versions, isn't it? We could think to drop support for this feature or we should adjust the role, so that it will register moodle via another way that works for Docker.

2024-04-30 11:14 UTC, Edmondi-Kacaj commented on ansible/roles/java/tasks/Debian.yml
Yes I agree with it, and I think will be better to use, `default-jdk` since we don't need Java, only for this case, and since also the jar command doesn't affect code, it doesn't care which Java version e are using, so I'm gonna use the `default-jdk` and it will be better.

2024-05-02 07:11 UTC, Edmondi-Kacaj commented
Hello @mirjan-hoffmann 

I adjust java, and we are using default-jdk,

About the tomcat I rollback, and I will delete it when I see how we can implement maybe in the docker version of moodle, since tomcat is used there too.

2024-05-02 07:42 UTC, mirjan-hoffmann commented on ansible/roles/java/tasks/Debian.yml
Ok for me. But maybe a common role like `geerlingguy.java` is more lightweight instead of implementing it yourself?

2024-05-02 07:44 UTC, mirjan-hoffmann commented on ansible/roles/backup/tasks/backup-edusharing-docker.yml
I think that it don't make sense to keep the complete backup. Since you remove support for edu-sharing < 7.x, you should also remove the backup process for these versions. Please only keep the Docker Backup

2024-05-02 07:46 UTC, mirjan-hoffmann requested changes
Since you remove support for edu-sharing < 7.x, it does not make sense to keep the tomcat role, because it just works for these versions.

Regarding usage of tomcat in `moodle-registration`: this will not work for edu-sharing >= 7.x

> We could think to drop support for this feature or we should adjust the role, so that it will register moodle via another way that works for Docker.

2024-05-02 07:51 UTC, Edmondi-Kacaj commented
I'm thinking in the next pull request to remove Tomcat and try to use Moodle in docker images, otherwise, I will delete both of them if is not possible.

So I'm working on that now, and for this pull request is OK, to merge and continue with other adjustments

2024-05-02 13:19 UTC, Edmondi-Kacaj commented
Hello @mirjan-hoffmann 

I've  got rid of the tomcat and moodle-registration roles and removed the alfresco backup from the backup role.

There are still some leftover variables that haven't been fully cleaned up yet. These are used in the edu-sharing role, which we'll tackle later when we optimize. But overall, I think this pull request is good to go for now.

We're merging it into the develop branch, it won't break the master branch. This way, we can keep moving forward and fix anything if needed. Once it's merged, we can continue with the optimization process.

2024-05-03 04:10 UTC, merged