Develop
TIBHannover/edu-sharing-box pull request #77
Opened 2024-05-22 15:50 UTC by Edmondi-Kacaj

Hello @mirjan-hoffmann 

In this pull request, I have made the following changes:

1. Removal of Support for edu-sharing Versions Below 7:

    The codebase has been updated to no longer support versions of edu-sharing earlier than version 7. This change simplifies the maintenance and ensures we can take advantage of newer features and improvements in the latest versions of edu-sharing.

2. Refactoring and Optimization of Scripts:

    Significant refactoring has been performed on various scripts to improve readability, maintainability, and efficiency.

2024-05-23 05:04 UTC, mirjan-hoffmann requested changes
`vagrant up` does not work, cannot test the installation

2024-05-23 05:08 UTC, mirjan-hoffmann commented on ansible/roles/java/tasks/get_java_home.yml
> +    warn: false  # Suppress warning messages
```Unsupported parameters for (ansible.legacy.command) module: warn```

=> not supported in newer ansible versions, please remove

2024-05-23 05:08 UTC, mirjan-hoffmann commented on ansible/roles/java/tasks/get_java_home.yml
> +    warn: false  # Suppress warning messages
```suggestion
```

2024-05-23 11:55 UTC, Edmondi-Kacaj commented
> `vagrant up` does not work, cannot test the installation

Yes from python3* they implemented a feature, prevents the installation of Python packages from pip.

So I Fixed it, by removing the `/usr/lib/python3.*/EXTERNALLY-MANAGED`, since Vagrant is used only for testing locally, I think it will be OK

So now You can test it again localy

2024-05-24 06:26 UTC, mirjan-hoffmann reviewed
these are far too many changes - I don't have the time to review them all

I just tested in the Vagrant VM:
* set up edu-sharing 8.1
* set up edu-sharing 8.0
* update from 8.0 to 8.1

this seem to work

other features were not tested by me

2024-05-24 07:57 UTC, Edmondi-Kacaj commented
> these are far too many changes - I don't have the time to review them all
> 
> I just tested in the Vagrant VM:
> 
> * set up edu-sharing 8.1
> * set up edu-sharing 8.0
> * update from 8.0 to 8.1
> 
> this seem to work
> 
> other features were not tested by me

Then we are going to keep this pull request, for a little bit more time, and I'm going to make a temp configuration in our test server, and test there, and if we see that everything is going to work as we wanted then we can merge it

So I'm going to keep this pull request to me, until we test all those changes in our Test server

2025-04-11 13:30 UTC, closed without merging

2025-04-11 13:30 UTC, Edmondi-Kacaj commented
Closing this pull request as we’ve decided to proceed with a different branch.
This PR is no longer needed.
See: [(NEW) Remove Support for edu-sharing Version < 7 and Script Refactoring](https://github.com/TIBHannover/edu-sharing-box/pull/95)